//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MFCApp.rc
//
#define Students_Dlg                    9
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MFCAPP_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDB_BITMAP1                     130
#define ALL_STUDENTS                    135
#define DELETE_STUDENT                  136
#define IDB_BITMAP2                     141
#define IDB_BITMAP3                     142
#define EMPLOYEE_MAIN                   143
#define EMPLOYEE_LIST                   147
#define IDC_                            1001
#define IDC_STATIC1                     1001
#define MISSING_COUNT                   1001
#define ADD_EMPLOYEE_HEADER             1001
#define IDC_BUTTON1                     1003
#define IDC_BUTTON2                     1004
#define IDC_BUTTON5                     1007
#define IDC_BUTTON3                     1008
#define IDC_BUTTON6                     1008
#define IDC_BUTTON4                     1009
#define IDC_BUTTON7                     1010
#define STUDENTS_LIST_BTN               1014
#define IDC_BUTTON8                     1014
#define IDC_BUTTON9                     1015
#define IDC_LIST2                       1025
#define FIRST_NAME                      1028
#define FIRST_NAME2                     1029
#define EDIT_STUDENT                    1029
#define FIRST_NAME3                     1030
#define ADD_EMPLOYEE                    1030
#define FIRST_NAME4                     1031
#define IDC_COMBO1                      1032
#define FIRST_NAME5                     1033
#define IDC_COMBO2                      1034
#define FIRST_NAME6                     1035
#define IDC_COMBO3                      1036
#define IDC_COMBO4                      1037
#define FIRST_NAME7                     1038
#define ADD_STDNT_HEADER                1039
#define FIRST_NAME8                     1039
#define FIRST_NAME9                     1040
#define IDC_COMBO5                      1041
#define IDC_COMBO6                      1042
#define IDC_COMBO7                      1043
#define IDC_COMBO8                      1044
#define FIRST_NAME10                    1045
#define FIRST_NAME11                    1046
#define FIRST_NAME12                    1047
#define FIRST_NAME13                    1048
#define FIRST_NAME14                    1049
#define FIRST_NAME15                    1050
#define FIRST_NAME16                    1051
#define IDC_COMBO9                      1052
#define IDC_COMBO10                     1053
#define IDC_COMBO11                     1054
#define IDC_COMBO12                     1055
#define FIRST_NAME17                    1056
#define FIRST_NAME18                    1057
#define FIRST_NAME19                    1058
#define FIRST_NAME20                    1059
#define FIRST_NAME21                    1060
#define LATES_COUNT                     1061
#define EMPLOYEE_LST_BTN                1062
#define ADD_TCHR_BTN                    1063
#define ADD_WORKER_BTN                  1064
#define DELETE_EMPLOYEE_BTN             1065
#define IMPORT_TCHR_BTN                 1066
#define EXPORT_TCHR_BTN                 1067
#define EXPORT_WRKR_BTN                 1068
#define IMPORT_WRKR_BTN                 1069
#define EMPLOYEE_LIST_CTRL              1069
#define EMP_PNAME_TXTBOX                1072
#define EMP_LNAME_TXTBOX                1073
#define EMP_ID_TXTBOX                   1074
#define EMP_GENDER_CBOX                 1075
#define EMP_BDAY_CBOX                   1076
#define EMP_BMONTH_CBOX                 1077
#define EMP_BYEAR_CBOX                  1078
#define EMP_STREET_TXTBOX               1079
#define EMP_CITY_TXTBOX                 1080
#define EMP_ZIPCODE_TXTBOX              1081
#define EMP_SALLERY_TXTBOX              1082
#define EMP_MARRIGE_CHKBOX              1083
#define EMP_KIDS_TXTBOX                 1084
#define EMP_ISWORKING_CHKBOX            1085
#define EMP_SDAY_CBOX                   1086
#define EMP_SMONTH_CBOX                 1087
#define EMP_SYEAR_CBOX                  1088
#define EMP_ROLE_TXTBOX                 1089
#define EMP_PROFFESSION_TXTBOX          1090
#define EMP_EDUCATION_CBOX              1091
#define EMP_ROLE_TXT                    1092
#define EMP_EDUCATOR_CHKBOX             1093
#define EMP_EDUCATION_CBOX2             1094
#define EMP_ASSOCIATION_CBOX            1094
#define EMP_PROFFESSION_TXT             1095
#define EMP_EDUCATION_TXT               1096
#define EMP_ASSOCIATION_TXT             1097
#define ADD_EMPLOYEE_BTN                1098
#define EMP_PHONE_TXTBOX                1099
#define ADD_STUDENT                     57665

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1099
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
